### ISSUE TITLE
MDT -  Service/Team not populated

### ISSUE THREAD

**Issue by PhilBarrett** [PulseTile/PulseTile#18]
![screenshot 2017-06-08 at 09 53 54](https://user-images.githubusercontent.com/12699244/26920278-671e57a4-4c30-11e7-9291-63b4995281b9.png)

**Comment by dkryvosheya** [comment]
http://prntscr.com/fhc79t - comes as an empty value from middleware;

**Comment by tony-shannon** [comment]
thanks @dkryvosheya 
If you are clear that this/other issues are related to the Ripple QEWD middleware and not a PulseTile UI issue, can you please raise them as issues there with @robtweed
https://github.com/RippleOSI/Ripple-Qewd/issues
and update this issue here accordingly with a link to that issue

Once he has accepted them, closed them there and retested in PulseTile, you can close them off here.

Many thanks in advance
Tony

**Comment by tony-shannon** [comment]
Please update this issue here accordingly with a link to the QEWD related  issue before closing it

**Comment by dkryvosheya** [comment]
This one is not particular QEWD issue, but data source (Marand or Ethercis) - what should I do in this case, @tony-shannon ?

**Comment by tony-shannon** [comment]
Best task as a QEWD issue for these ones.. we can pass onto DB team if
confirmed.
Thanks
T

**Comment by dkryvosheya** [comment]
Duplicated in QEWD repository: https://github.com/RippleOSI/Ripple-Qewd/issues/37
QEWD - MDT - Service / team data is not populated;
