### ISSUE TITLE
tidy up core PulseTile repo

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile#33]
@dkryvosheya 
related to issue https://github.com/PulseTile-Plugins/Silver-Plugins/issues/3

1)
when looking here;
https://github.com/PulseTile/PulseTile/tree/master/src
Need to check if the 
cornerstone
+
videochat 
folders can be moved to silver plugins?

2)
Can we rename this rippleui folder to pulsetileui please 
https://github.com/PulseTile/PulseTile/tree/master/src/app/rippleui
to 
https://github.com/PulseTile/PulseTile/tree/master/src/app/pulsetileui  please

**Comment by PhilBarrett** [comment]
@dkryvosheya please can you explain rationale behind Dicom within https://github.com/PulseTile/PulseTile/tree/develop/src/app/rippleui/pages

Please can you remove the folders that are meant to be in the silver plugins as there appears to be duplication.

**Comment by tony-shannon** [comment]
NB @dkryvosheya 
We have set up 2 new Plugin repos for the webRTC & DICOM (cornerstone) modules;
https://github.com/PulseTile-Plugins/Carbon-Plugin-WebRTC
https://github.com/PulseTile-Plugins/Carbon-Plugin-DICOM
thanks for moving their codebases there
Tony

**Comment by dkryvosheya** [comment]
@PhilBarrett we're keeping everything in one place - since for development purposes we need to have every currently present heading in place in the main repo. 

This way if we, for example, need to change something within some heading that's not listed as core - we don't need to switch between the repositories - for solely development purposes it's easier for us to work with the complete bundle of headings. This can be cleaned up when we are 100% done with codebase polishing, but for now I would suggest to keep every heading within this repo. 

As for Dicom - we're keeping Dicom (Images heading) files, like, image list HTML file, single image HTML file, etc within this particular folder, while Cornerstone folder consists of library files which we took from Cornerstone's repo to work with on our end. 

Hope this clarifies, if there is any questions - please let me know :-)

@tony-shannon Thanks, Tony!

**Comment by tony-shannon** [comment]
ok thanks @dkryvosheya 

So 2 suggestions;
1  -would the develop branch have all the headings while the master branch just contain the core?
I appreciate you need easy access to all during development

2- so then the DICOM/Images heading file would be suitable for the Silver-Plugins Repo , while the Cornerstone based material may be best in the https://github.com/PulseTile-Plugins/Carbon-Plugin-DICOM folder

thanks

**Comment by dkryvosheya** [comment]
Will tidy up the repo's as soon as we're done with all the outstanding issues (only one left at the moment - related to Events data flow & UI changes)

**Comment by dkryvosheya** [comment]
Tidied up the repository according to the prompt above; 
Additionally updated documentation according to the latest changes related to Events heading; 
Please review @tony-shannon;

**Comment by PhilBarrett** [comment]
@dkryvosheya thanks for this. 
Events looks good 
The readme files for both webRTC and Dicom/cornerstone need more information and/or pointing to docs.pulsetile.com though please.

**Comment by dkryvosheya** [comment]
Sure, I'll update the repos.

**Comment by PhilBarrett** [comment]
Thanks @dkryvosheya , those have been merged.
