### ISSUE TITLE
view dropdowns are not visible fully in patient list for the last person

### ISSUE THREAD

**Issue by poojaparasharam** [PulseTile/PulseTile#50]
![patient-list](https://user-images.githubusercontent.com/22934002/31985278-281d3196-b982-11e7-8883-65f497b48597.png)
In patient list for the last person , when i click view button the dropdown list is not showing all options,its hiding in footer.

please find attachment.

Regards,
Pooja

**Comment by anna-otrokhova** [comment]
@poojaparasharam 

Thank you for details. We will check and let you know during the next week.

**Comment by anna-otrokhova** [comment]
@poojaparasharam 

The issue was fixed here (You should switch to Angular version first, the instruction can be found here in comments https://github.com/PulseTile/PulseTile/issues/46 ) http://dev.ripple.foundation/ . Could you check it please?

@tony-shannon 
Tony, could you help me, please? Shall we transfer the fixes to http://showcase.ripple.foundation/#/charts too?

**Comment by tony-shannon** [comment]
thanks @anna-otrokhova 
that looks like its working to me now on dev,  so you can update the showcase box

You can let @poojaparasharam know when you update the codebase here, so he can pull down and test locally 

thanks

Tony

**Comment by tony-shannon** [comment]
NB @poojaparasharam please note that our dev box is for internal testing purposes, not wider usage, thanks, Tony

**Comment by anna-otrokhova** [comment]
@poojaparasharam 
 The changes were successfully transferred to showcase box.

Can this issue be closed?
